"""initial schema operadores

Revision ID: 3874fb3cfa95
Revises: 
Create Date: 2025-12-01 19:39:41.432161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3874fb3cfa95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('domicilio', sa.String(length=255), server_default='', nullable=False),
    sa.Column('telefono', sa.String(length=50), server_default='', nullable=False),
    sa.Column('no_imss', sa.String(length=50), server_default='', nullable=False),
    sa.Column('rfc', sa.String(length=50), server_default='', nullable=False),
    sa.Column('no_licencia', sa.String(length=50), server_default='', nullable=False),
    sa.Column('fecha_venc_licencia', sa.Date(), nullable=True),
    sa.Column('sueldo_op_1', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('viaticos_op_1', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('sueldo_op_2', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('viaticos_op_2', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('viaje_especial', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('kms_acumulados', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('viaticos_por_km', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('sueldo_por_km', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('mexico', sa.String(length=20), server_default='', nullable=False),
    sa.Column('exp_ver', sa.String(length=20), server_default='', nullable=False),
    sa.Column('exp_lc', sa.String(length=20), server_default='', nullable=False),
    sa.Column('exp_tux', sa.String(length=20), server_default='', nullable=False),
    sa.Column('importado', sa.String(length=20), server_default='', nullable=False),
    sa.Column('local', sa.String(length=20), server_default='', nullable=False),
    sa.Column('patios', sa.String(length=20), server_default='', nullable=False),
    sa.Column('slp_altamira', sa.String(length=20), server_default='', nullable=False),
    sa.Column('ramos_altamira', sa.String(length=20), server_default='', nullable=False),
    sa.Column('slp_lc', sa.String(length=20), server_default='', nullable=False),
    sa.Column('sal_lzc', sa.String(length=20), server_default='', nullable=False),
    sa.Column('sal_ver', sa.String(length=20), server_default='', nullable=False),
    sa.Column('sal_altamira', sa.String(length=20), server_default='', nullable=False),
    sa.Column('resguardo', sa.String(length=20), server_default='', nullable=False),
    sa.Column('ayuda_escolar', sa.String(length=20), server_default='', nullable=False),
    sa.Column('tipo_carro', sa.String(length=50), server_default='', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'codigo', name='uq_operator_client_codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operators')
    op.drop_table('clients')
    # ### end Alembic commands ###
