"""add liquidacion deducciones

Revision ID: 3cbd65b9b0f8
Revises: efed8151c7fc
Create Date: 2025-12-19 01:57:44.428566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbd65b9b0f8'
down_revision = 'efed8151c7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'liquidacion_deducciones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('liquidacion_id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=64), nullable=True),
        sa.Column('label', sa.String(length=120), nullable=False),
        sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint('monto >= 0', name='ck_liq_ded_monto_nonneg'),
        sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('liquidacion_deducciones', schema=None) as batch_op:
        batch_op.create_index('ix_liq_ded_liq_created', ['liquidacion_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacion_deducciones_liquidacion_id'), ['liquidacion_id'], unique=False)

    # 1) Agregar columnas como NULL (para que no truene si ya hay filas)
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deducciones_total', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('neto_operador', sa.Numeric(precision=14, scale=2), nullable=True))

    # 2) Backfill: filas existentes
    # - deducciones_total: 0
    # - neto_operador: total (porque antes no había deducciones)
    op.execute("UPDATE liquidaciones SET deducciones_total = 0 WHERE deducciones_total IS NULL;")
    op.execute("UPDATE liquidaciones SET neto_operador = COALESCE(total, 0) WHERE neto_operador IS NULL;")

    # 3) Ahora sí: imponer NOT NULL
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.alter_column('deducciones_total', existing_type=sa.Numeric(precision=14, scale=2), nullable=False)
        batch_op.alter_column('neto_operador', existing_type=sa.Numeric(precision=14, scale=2), nullable=False)
    # ### end Alembic commands ###

