"""destinationsv2

Revision ID: 422d7dfda963
Revises: 53ac98550d16
Create Date: 2025-12-14 21:38:24.002610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422d7dfda963'
down_revision = '53ac98550d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_client_id'))
        batch_op.drop_constraint(batch_op.f('uq_destinations_client_codigo'), type_='unique')
        batch_op.create_unique_constraint('uq_destination_client_codigo', ['client_id', 'codigo'])
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_destination_client_codigo', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_destinations_client_codigo'), ['client_id', 'codigo'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_destinations_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###
