"""Modificación eliminar pagos

Revision ID: 4fc6051b580f
Revises: c012c075146b
Create Date: 2025-12-19 10:08:59.020895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fc6051b580f'
down_revision = 'c012c075146b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.drop_column('pagado')
        batch_op.drop_column('pagado_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pagado', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
