"""create destinations catalog

Revision ID: 53ac98550d16
Revises: 95b82a6f1a54
Create Date: 2025-12-14 20:09:53.509792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ac98550d16'
down_revision = '95b82a6f1a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('plaza', sa.String(length=80), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=True),
    sa.Column('aplica_iva', sa.Boolean(), nullable=False),
    sa.Column('iva_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('aplica_retencion', sa.Boolean(), nullable=False),
    sa.Column('retencion_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'codigo', name='uq_destinations_client_codigo')
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destinations_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_client_id'))

    op.drop_table('destinations')
    # ### end Alembic commands ###
