"""add liquidaciones + client_counters

Revision ID: 600f22d36e30
Revises: 90eba2722e32
Create Date: 2025-12-15 02:05:50.637549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600f22d36e30'
down_revision = '90eba2722e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_counters',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_folio_seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('liquidaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('folio_num', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=32), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('car_type', sa.String(length=8), nullable=True),
    sa.Column('kms', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aplica_iva', sa.Boolean(), nullable=False),
    sa.Column('iva_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('iva_monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aplica_retencion', sa.Boolean(), nullable=False),
    sa.Column('retencion_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('retencion_monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'posted', 'liquidated', 'cancelled')", name='ck_liq_status_valid'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'folio', name='uq_liq_client_folio'),
    sa.UniqueConstraint('client_id', 'folio_num', name='uq_liq_client_folio_num')
    )
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.create_index('ix_liq_client_activo', ['client_id', 'activo'], unique=False)
        batch_op.create_index('ix_liq_client_fecha', ['client_id', 'fecha'], unique=False)
        batch_op.create_index('ix_liq_client_status', ['client_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidaciones', schema=None) as batch_op:
        batch_op.drop_index('ix_liq_client_status')
        batch_op.drop_index('ix_liq_client_fecha')
        batch_op.drop_index('ix_liq_client_activo')

    op.drop_table('liquidaciones')
    op.drop_table('client_counters')
    # ### end Alembic commands ###
