"""add guides

Revision ID: 90eba2722e32
Revises: c8c9c3240df4
Create Date: 2025-12-14 22:10:56.897585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90eba2722e32'
down_revision = 'c8c9c3240df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('car_type', sa.String(length=10), server_default='', nullable=False),
    sa.Column('kms', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('aplica_iva', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('iva_pct', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('iva_monto', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('aplica_retencion', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('retencion_pct', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('retencion_monto', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'folio', name='uq_guide_client_folio')
    )
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guides_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_guides_client_operator_date', ['client_id', 'operator_id', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guides_status'))
        batch_op.drop_index(batch_op.f('ix_guides_operator_id'))
        batch_op.drop_index(batch_op.f('ix_guides_fecha'))
        batch_op.drop_index(batch_op.f('ix_guides_destination_id'))
        batch_op.drop_index('ix_guides_client_operator_date')
        batch_op.drop_index(batch_op.f('ix_guides_client_id'))
        batch_op.drop_index(batch_op.f('ix_guides_car_id'))

    op.drop_table('guides')
    # ### end Alembic commands ###
