"""add cars and car type configs

Revision ID: c330260fa78b
Revises: 3874fb3cfa95
Create Date: 2025-12-10 19:21:56.051017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c330260fa78b'
down_revision = '3874fb3cfa95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_type_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('car_type', sa.String(length=10), nullable=False),
    sa.Column('sueldo_por_km', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('viaticos_por_km', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('sueldo_ayudante', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('viaticos_ayudante', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('viaje_especial', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('mexico', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('exp_ver', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('exp_lc', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('exp_tux', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('importado', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('local', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('patios', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('slp_altamira', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('ramos_altamira', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('slp_lc', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('sal_lzc', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('sal_ver', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('sal_altamira', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('resguardo', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'car_type', name='uq_car_type_config_client_type')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('capacidad', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('km_acum', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('fec_u_sal', sa.Date(), nullable=True),
    sa.Column('lt_dies_ac', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('ingre_acum', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('operador', sa.String(length=120), server_default='', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'codigo', name='uq_car_client_codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('car_type_configs')
    # ### end Alembic commands ###
