"""Nuevas columnas en operadores

Revision ID: e6f15edb911a
Revises: 600f22d36e30
Create Date: 2025-12-18 23:40:01.841489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f15edb911a'
down_revision = '600f22d36e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_electronico', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('gafete_aduana', sa.String(length=80), server_default='', nullable=False))
        batch_op.add_column(sa.Column('apto_medico_licencia', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tiene_seguro', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.drop_column('tiene_seguro')
        batch_op.drop_column('apto_medico_licencia')
        batch_op.drop_column('gafete_aduana')
        batch_op.drop_column('correo_electronico')

    # ### end Alembic commands ###
