"""Nueva columna de carro

Revision ID: efed8151c7fc
Revises: e6f15edb911a
Create Date: 2025-12-18 23:48:20.834990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efed8151c7fc'
down_revision = 'e6f15edb911a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie', sa.String(length=80), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('serie')

    # ### end Alembic commands ###
